version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: tasty-track-mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-vl:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: tasty-track-redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always
    volumes:
      - redis-vl:/data


volumes:
  mysql-vl:
    driver: local
  redis-vl:
    driver: local

