version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: tasty-track-mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-vl:/var/lib/mysql

volumes:
  mysql-vl:
    driver: local
